# Generated by Django 3.0.3 on 2020-04-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0002_auto_20200413_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crh',
            old_name='opPerf',
            new_name='op_perf',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_birth',
            field=models.DateTimeField(),
        ),
    ]
