# Generated by Django 3.0.3 on 2020-04-15 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0003_auto_20200415_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='crh',
            name='date_crh',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
