# Generated by Django 3.0.3 on 2020-04-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0004_crh_date_crh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crh',
            name='op_perf',
        ),
    ]
