# Generated by Django 3.0.3 on 2020-04-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0006_crh_op_perf'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='crh',
            constraint=models.UniqueConstraint(fields=('employee', 'date_crh'), name='unique_crh'),
        ),
    ]
