# Generated by Django 3.0.3 on 2020-04-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0007_auto_20200415_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crh',
            name='date_crh',
            field=models.DateField(auto_now_add=True),
        ),
    ]
