# Generated by Django 3.0.3 on 2020-04-15 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0008_auto_20200415_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crh',
            name='date_crh',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
