# Generated by Django 3.0.3 on 2020-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0010_auto_20200415_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crh',
            name='op_perf',
            field=models.CharField(choices=[('SUPERIOR TO EXPECTATIONS', 'Se'), ('ABOVE EXPECTATIONS', 'Ae'), ('MEETING EXPECTATIONS', 'Me'), ('PARTIALLY MEETING EXPECTATIONS', 'Pm'), ('BELOW EXPECTATIONS', 'Be')], default='MEETING EXPECTATIONS', max_length=50),
        ),
    ]
