# Generated by Django 3.0.3 on 2020-04-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0011_auto_20200415_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crh',
            name='op_perf',
            field=models.CharField(choices=[('SUPERIOR TO EXPECTATIONS', 'SUPERIOR TO EXPECTATIONS'), ('ABOVE EXPECTATIONS', 'ABOVE EXPECTATIONS'), ('MEETING EXPECTATIONS', 'MEETING EXPECTATIONS'), ('PARTIALLY MEETING EXPECTATIONS', 'PARTIALLY MEETING EXPECTATIONS'), ('BELOW EXPECTATIONS', 'BELOW EXPECTATIONS')], default='MEETING EXPECTATIONS', max_length=50),
        ),
    ]
