# Generated by Django 3.0.3 on 2020-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0012_auto_20200415_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_birth',
            field=models.DateField(),
        ),
    ]
