# Generated by Django 3.0.3 on 2020-04-29 15:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0013_auto_20200427_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='crh',
            name='comment',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='crh',
            name='potencial',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='company_seniority',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='employee',
            name='exp_from_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='maturity',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='profil',
            field=models.CharField(choices=[('Solution Building', 'SB'), ('Business Analyst', 'BA'), ('Project manager', 'PM'), ('Tester', 'TE'), ('Production', 'PR')], default='Solution Building', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('domain', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rhapp.Domain')),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rhapp.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rhapp.Employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Doma',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rhapp.Domain'),
        ),
        migrations.AddField(
            model_name='employee',
            name='proj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rhapp.Project'),
        ),
    ]
