# Generated by Django 3.0.3 on 2020-04-29 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0014_auto_20200429_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Doma',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_birth',
        ),
        migrations.AddField(
            model_name='employee',
            name='Dom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='rhapp.Domain'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='crh',
            name='potencial',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='domain',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='rhapp.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='proj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='rhapp.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='rhapp.Domain'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='rhapp.Employee'),
        ),
    ]
