# Generated by Django 3.0.3 on 2020-04-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0015_auto_20200429_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_seniority',
            field=models.DateField(default=None, null=True),
        ),
    ]
