# Generated by Django 3.0.3 on 2020-04-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0016_auto_20200429_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Dom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rhapp.Domain'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='exp_from_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='proj',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rhapp.Project'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
