# Generated by Django 3.0.3 on 2020-05-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0018_auto_20200429_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Dom',
        ),
    ]
