# Generated by Django 3.0.3 on 2020-05-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0019_remove_employee_dom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crh',
            name='comment',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
