# Generated by Django 3.0.3 on 2020-05-01 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhapp', '0020_auto_20200501_1430'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='crh',
            name='unique_crh',
        ),
        migrations.RemoveField(
            model_name='crh',
            name='date_crh',
        ),
        migrations.RemoveField(
            model_name='crh',
            name='potencial',
        ),
        migrations.AddField(
            model_name='crh',
            name='crh_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='crh',
            name='potential',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='crh',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhapp.Employee', unique_for_month='crh_date'),
        ),
        migrations.AddConstraint(
            model_name='crh',
            constraint=models.UniqueConstraint(fields=('employee', 'crh_date'), name='unique_crh'),
        ),
    ]
